Android: fix compilation libpng-1.6.37 (missing arm/palette_neon_intrinsics.c)
undefined reference to `png_riffle_palette_neon'
undefined reference to `png_do_expand_palette_rgba8_neon'
undefined reference to `png_do_expand_palette_rgb8_neon'